### ISSUE TITLE
[Question] In EF Core I can use SQLite DB in memory. In what cases your project will be better than use database in memory ?

### ISSUE THREAD

**Issue by tomaszprasolek** [huysentruitw/entity-framework-core-mock#17]

**Comment by huysentruitw** [comment]
This library is a port from my EF 6 compatible mocking library where using in-memory SQLite was not that straight forward.

The reason why I did the port was because using SQLite can sometimes be overkill and start feeling like integration testing instead (but on the wrong database if you're using SQL otherwise). Also this library simplifies seeding and mostly result in a smaller test arrangement. On the other hand, it doesn't check foreign key relations so it's not the perfect solution for evertthing.

See it as another tool in the toolbox to choose from.

**Comment by tomaszprasolek** [comment]
I understand. Thanks for your answer.

**Comment by huysentruitw** [comment]
You're welcome! 👍
